
k_bootstrap_code = 'bootstrap_code'
k_MBR = 'MBR'
k_Partition = 'Partition'
k_PartitionEntry = 'PartitionEntry'
k_PartitionEntries = 'PartitionEntries'
k_status = 'status'

k_starting_chs_address = 'starting_chs_address'
k_ignored = '__ignored__'
k_partition_type = 'partition_type'
k_ending_chs_address = 'ending_chs_address'
k_first_sector_address = 'first_sector_address'
k_first_byte_address = 'first_byte_address'
k_number_of_sectors = 'number_of_sectors'
k_size = 'size'

k_boot_signature = 'boot_signature'

k_FAT32BootSector = 'FAT32BootSector'
k_jump_instruction = 'jump_instruction'
k_OEM_name = 'OEM_name'
k_bytes_per_sector = 'bytes_per_sector'
k_sectors_per_cluster = 'sectors_per_cluster'
k_number_of_reserved_sectors = 'number_of_reserved_sectors'
k_number_of_FATs = 'number_of_FATs'
k_media_descriptor = 'media_descriptor'
k_sectors_per_track = 'sectors_per_track'
k_number_of_heads = 'number_of_heads'
k_number_of_hidden_sectors = 'number_of_hidden_sectors'
k_sectors_per_FAT = 'sectors_per_FAT'
k_drive_description = 'drive_description'
k_version = 'version'
k_cluster_number_of_root_directory_start =\
    'cluster_number_of_root_directory_start'
k_sector_number_of_FS_info_sector = 'sector_number_of_FS_info_sector'
k_sector_number_of_boot_sectors_backup = 'sector_number_of_boot_sectors_backup'
k_drive_number = 'drive_number'
k_extended_boot_signature = 'extended_boot_signature'
k_volume_id = 'volume_id'
k_volume_label = 'volume_label'
k_filesystem_type = 'filesystem_type'

k_FAT32FileAllocationTable = 'FAT32FileAllocationTable'

k_Drive = 'Drive'

k_FAT32 = 'FAT32'
k_NTFS = 'NTFS'
k_ExtendedPartition = 'ExtendedPartition'

k_reserved = 'reserved'

k_FAT32DirectoryTableEntry = 'FAT32DirectoryTableEntry'
k_short_file_name = 'short_file_name'
k_short_extension = 'short_extension'
k_attribute = 'attribute'
k_create_time_10ms = 'create_time_10ms'
k_create_time = 'create_time'
k_create_date = 'create_date'
k_access_date = 'access_date'
k_higher_cluster = 'higher_cluster'
k_modify_time = 'modify_time'
k_modify_date = 'modify_date'
k_lower_cluster = 'lower_cluster'
k_file_length = 'file_length'

k_FAT32LongFilenameEntry = 'FAT32LongFilenameEntry'
k_sequence_number = 'sequence_number'
k_name_1 = 'name_1'
k_type = 'type'
k_checksum = 'checksum'
k_name_2 = 'name_2'
k_first_cluster = 'first_cluster'
k_name_3 = 'name_3'

k_filename = 'filename'
k_full_path = 'full_path'
k_path = 'path'
k_extension = 'k_extension'
k_cluster_list = 'cluster_list'
